#!/bin/bash

# Manual Azure App Registration Commands
# Copy and paste these commands one by one if you prefer manual setup

echo "Manual Azure App Registration Setup Commands"
echo "==========================================="
echo ""
echo "1. Login to Azure (if not already logged in):"
echo "   az login"
echo ""
echo "2. Check your current subscription:"
echo "   az account show"
echo ""
echo "3. Create API App Registration:"
echo "   API_APP_ID=\$(az ad app create \\"
echo "       --display-name \"FastMCP Auth API\" \\"
echo "       --identifier-uris \"api://fastmcp-auth-api\" \\"
echo "       --query appId --output tsv)"
echo ""
echo "4. Create Web App Registration:"
echo "   WEB_APP_ID=\$(az ad app create \\"
echo "       --display-name \"FastMCP Auth Web\" \\"
echo "       --spa-redirect-uris \"http://localhost:3000\" \\"
echo "       --query appId --output tsv)"
echo ""
echo "5. Get your Tenant ID:"
echo "   TENANT_ID=\$(az account show --query tenantId --output tsv)"
echo ""
echo "6. Display the values:"
echo "   echo \"Web App ID: \$WEB_APP_ID\""
echo "   echo \"API App ID: \$API_APP_ID\""
echo "   echo \"Tenant ID: \$TENANT_ID\""
echo ""
echo "7. Update src/authConfig.js with these values:"
echo "   - Replace REPLACE_WITH_YOUR_CLIENT_ID with \$WEB_APP_ID"
echo "   - Replace REPLACE_WITH_YOUR_TENANT_ID with \$TENANT_ID"
echo "   - Replace REPLACE_WITH_YOUR_API_CLIENT_ID with \$API_APP_ID"
echo ""
echo "Note: You may need to manually configure API permissions and grant admin consent in the Azure Portal."
